// Writes src/data/cycles.ts from the hand-picked puzzle files. Usage: npx tsx scripts/apply.ts
import { readFileSync, writeFileSync } from 'node:fs';
const RESTLESS = ['hall.e', 'library.n', 'mirrors.e', 'gallery.n', 'conservatory.w', 'cellar.e', 'clock.e', 'upper.n', 'upper.w', 'upper.e'];
const files: Record<number, string> = JSON.parse(readFileSync('scripts/puzzles.json', 'utf8'));
const out: Record<string, Record<number, string[]>> = {};
for (const id of RESTLESS) out[id] = {};
for (const p of [0, 1, 2, 3, 4]) {
  const cyc: Record<string, string[]> = (files as any)[p] ?? {};
  for (const id of RESTLESS) out[id][p] = cyc[id] ?? [];
}
let s = `import type { DoorDef } from '../game/types';
/**
 * Lantern cycles per restless door, per clock phase (0 = 9 PM ... 4 = midnight). An empty list means the door is dead in that phase.
 * Generated by scripts/tune2.ts + scripts/apply.ts and verified by tests/state.test.ts (BFS solver: solvable, no soft locks).
 */
export const CYCLES: Record<string, DoorDef['cycles']> = {\n`;
for (const id of RESTLESS) {
  s += `  '${id}': {\n`;
  for (const p of [0, 1, 2, 3, 4]) s += `    ${p}: ${JSON.stringify(out[id][p]).replace(/"/g, "'").replace(/,/g, ', ')},\n`;
  s += `  },\n`;
}
s += `};\n`;
writeFileSync('src/data/cycles.ts', s);
console.log('written');
