import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 960, height: 540 } });
const logs = new Set();
page.on('console', (m) => { if (m.type() === 'error') logs.add(m.text().slice(0, 200)); });
page.on('pageerror', (e) => logs.add('pageerror ' + e.message));
await page.goto('http://localhost:5173/?q=low');
await page.waitForFunction(() => window.__game && window.__game.mode === 'title', null, { timeout: 180000 });
await page.evaluate(() => localStorage.clear());
await page.click('text=New Game');
await page.waitForFunction(() => window.__game.mode === 'play');
const pos = () => page.evaluate(() => ({ x: +window.__game.player.pos.x.toFixed(2), z: +window.__game.player.pos.z.toFixed(2), yaw: +window.__game.player.yaw.toFixed(2), room: window.__game.state.room }));
console.log('start', await pos());
await page.keyboard.down('KeyW'); await page.waitForTimeout(6000); await page.keyboard.up('KeyW');
console.log('after W 6s', await pos());
await page.keyboard.down('ArrowLeft'); await page.waitForTimeout(1500); await page.keyboard.up('ArrowLeft');
console.log('after look left', await pos());
await page.keyboard.down('KeyW'); await page.waitForTimeout(15000); await page.keyboard.up('KeyW');
console.log('after long walk (should stay in hall bounds x[-4.5,4.5] z[-5.5,5.5])', await pos());
await page.keyboard.press('Escape'); await page.waitForTimeout(500);
console.log('paused?', await page.evaluate(() => window.__game.mode), await page.evaluate(() => window.__game.ui.overlayName));
await page.click('text=Resume'); await page.waitForTimeout(500);
console.log('resumed?', await page.evaluate(() => window.__game.mode));
await page.keyboard.press('Tab'); await page.waitForTimeout(500);
console.log('journal?', await page.evaluate(() => window.__game.mode));
await page.screenshot({ path: 'shots/journal.png', timeout: 120000 });
await page.keyboard.press('Tab'); await page.waitForTimeout(300);
console.log('closed?', await page.evaluate(() => window.__game.mode));
console.log([...logs].join('\n') || 'no console errors');
await browser.close();
