import type { DoorDef } from '../game/types';
/**
 * Lantern cycles per restless door, per clock phase (0 = 9 PM ... 4 = midnight). An empty list means the door is dead in that phase.
 * Generated by scripts/tune2.ts + scripts/apply.ts and verified by tests/state.test.ts (BFS solver: solvable, no soft locks).
 */
export const CYCLES: Record<string, DoorDef['cycles']> = {
  'hall.e': {
    0: ['dining.w', 'kitchen.w'],
    1: [],
    2: [],
    3: [],
    4: [],
  },
  'library.n': {
    0: ['kitchen.w', 'dining.e', 'mirrors.s'],
    1: ['conservatory.w', 'mirrors.e', 'gallery.n'],
    2: ['kitchen.s', 'hall.w', 'gallery.w'],
    3: [],
    4: [],
  },
  'mirrors.e': {
    0: [],
    1: ['library.s', 'clock.s', 'hall.w'],
    2: [],
    3: [],
    4: [],
  },
  'gallery.n': {
    0: [],
    1: ['library.e', 'dining.e', 'kitchen.w'],
    2: ['cellar.e', 'conservatory.w', 'library.n'],
    3: [],
    4: [],
  },
  'conservatory.w': {
    0: [],
    1: [],
    2: [],
    3: [],
    4: [],
  },
  'cellar.e': {
    0: [],
    1: [],
    2: ['library.s', 'clock.e', 'gallery.n'],
    3: [],
    4: ['library.s', 'upper.w'],
  },
  'clock.e': {
    0: [],
    1: [],
    2: ['conservatory.e', 'crypt.n', 'library.s'],
    3: [],
    4: ['hall.w', 'gallery.e'],
  },
  'upper.n': {
    0: [],
    1: [],
    2: [],
    3: [],
    4: ['library.n', 'cellar.e', 'gallery.e'],
  },
  'upper.w': {
    0: [],
    1: [],
    2: [],
    3: [],
    4: ['dining.e', 'library.e'],
  },
  'upper.e': {
    0: [],
    1: [],
    2: [],
    3: [],
    4: ['library.n', 'atticstair.s'],
  },
};
